### ISSUE TITLE
vim-textobj-user not working with vim-operator-replace

### ISSUE THREAD

**Issue by norcalli** [kana/vim-textobj-user#43]
As you can tell, I'm an avid user of your plugins, but it seems as if there's a problem.

I've tried with a few different textobj like line and quote, and it seems as if replace doesn't work only with user defined textobjects. For example if the textobj is quote and replace is mapped to `_`, then in the middle of a quote `"+_iq` fails pulling instead the `"` register, but `"+_i"` works fine.

Is this a known bug?

**Comment by kana** [comment]
Does the problem happen for all user defined text objects or only for specific text objects?

**Comment by norcalli** [comment]
Sorry for the delay. I haven't done exhaustive searching, but all of the following have failed:
```
	"kana/vim-textobj-user": {},
	"kana/vim-textobj-indent": {},
	"kana/vim-textobj-line": {},
	"kana/vim-textobj-entire": {},
	"kana/vim-textobj-lastpat": {},
	"norcalli/textobj-gitgutter": {},
	"Julian/vim-textobj-brace": {},
	"beloglazov/vim-textobj-quotes": {},
```

So it appears so, yes.

**Comment by kana** [comment]
Thank you for the list.  I'll investigate the problem soon.

**Comment by kana** [comment]
I found the cause of the problem.  The problem happens when vim-operator-replace is used with *any* text object defined with vim-textobj-user.  But it's not possible to fix the problem by tweaking vim-textobj-user.  Workarounds are necessary to vim-operator-user and vim-operator-replace.

Suppose that `_` is mapped to vim-operator-replace and `au` is mapped to a user-defined text object.  If user typed `"a_au`, what actually executed is something like `"ag@:normal! vhhjjkkll<CR>`.

vim-operator-replace uses `v:register` to know what register is specified.  But `v:register` contains the *last* specified register.  In this example, `v:register` contains `a` until executing `:normal!`, then it is overwritten with `"` after executing `:normal!`.  And built-in text objects don't overwrite `v:register`.  That's why wrong register is used.

I'll fix the problem later.

**Comment by norcalli** [comment]
Sounds good. Thank you for investigating further. I thought I recognized
this problem in operator before, and I too will look into a solution.

Thank you,
Ashkan Kiani

**Comment by norcalli** [comment]
Thank you! I tried it out and it works!
