### ISSUE TITLE
Allow other modifiers

### ISSUE THREAD

**Issue by blasco** [kana/vim-textobj-user#71]
Is it possible to use other modifiers rather than [a,i] ?
I like the idea of having other modifier, kind of what targets.vim does with i,I,a,A

I tried to add another kind of line text object like this:

```
call textobj#user#plugin('line', {
\      '-': {
\        'select-a': 'al', 'select-a-function': 'textobj#line#select_a',
\        'select-i': 'il', 'select-i-function': 'textobj#line#select_I',
\        'select-I': 'Il', 'select-I-function': 'textobj#line#select_I'
\      },
\    })

```

But doesn't work. Is this possible somehow? Any guidance would be very much appreciated.

**Comment by kana** [comment]
Yes, it's possible. For example:

```vim
call textobj#user#plugin('line', {
\      'a': {'select': 'al', 'select-function': 'textobj#line#select_a'},
\      'A': {'select': 'Al', 'select-function': 'textobj#line#select_A'},
\      'i': {'select': 'il', 'select-function': 'textobj#line#select_i'},
\      'I': {'select': 'Il', 'select-function': 'textobj#line#select_I'},
\    })
```

This should define

- `al`, `Al`, `il` and`Il` as the default key mappings
- `<Plug>(textobj-line-a)`, `<Plug>(textobj-line-A)` and so forth for end user customization

`A` and `I` are not standard modifiers for text objects, so that vim-textobj-user doesn't provide a convenient way — like `select-I` in your example — to define text objects with such modifiers.

**Comment by blasco** [comment]
Great! Thank you, now it works like a charm.
